### ISSUE TITLE
error when training

### ISSUE THREAD

**Issue by ChrisXULC** [CoderYinDaqiang/OdegVul#1]
usr/local/lib/python3.10/dist-packages/torch/nn/modules/rnn.py:71: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "
  0% 0/40 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/OdegVul-main/script/train_model_Odeg.py", line 248, in <module>
    train_model(dataset_name)
  File "/content/OdegVul-main/script/train_model_Odeg.py", line 183, in train_model
    adj = get_adj(batch_size).cuda()
  File "/content/OdegVul-main/script/my_util.py", line 216, in get_adj
    with open(file_name) as file_object:
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/pregraph/graph.txt'

how to get this file?

**Comment by CoderYinDaqiang** [comment]
obtained through PDG Generator
